// <auto-generated />
namespace SymposiumVoting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Class_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Class_added));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300536595_Class_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
