// <auto-generated />
namespace SymposiumVoting.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class remove_constructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_constructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300524342_remove_constructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
